app/admin/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from app.utils import (
    requires_role,
    get_user_by_username,
    get_user_by_email,
    create_user,
    get_delta_hours,
)
from flask_login import current_user
from app.models import (
    Roles,
    Activity,
    User,
    Facility,
    Activities,
    Facilities,
    Days,
)
from app import db, hasher, stripe
from sqlalchemy import select
import sqlalchemy
from app.forms import (
    EditActivityForm,
    EditUserForm,
    EditFacilityForm,
    EditEmployeeForm,
    AddEmployeeForm,
    PricingForm,
)

admin = Blueprint(
    "admin",
    __name__,
    template_folder="templates",
    static_folder="static",
    url_prefix="/admin",
)


@admin.route("/")
@requires_role(Roles.ADMIN)
def index():
    return render_template("m_dashboard.html")


@admin.route("/activities")
@requires_role(Roles.ADMIN)
def activities():
    activity_list = db.session.execute(select(Activity)).all()
    # .all() gives results in a list of (object,) tuples
    activity_list = [act[0].admin_data() for act in activity_list]

    if len(activity_list) == 0:
        return render_template(
            "show_db_data.html",
            title="Activities",
            edit_action="admin.edit_activity",
        )

    return render_template(
        "show_db_data.html",
        title="Activities",
        columns=activity_list[0].keys(),
        data=activity_list,
        edit_action="admin.edit_activity",
        delete_from="activity",
        message="Deleting an Activity does not effect already booked sessions.",
    )


@admin.route("/activities/edit", methods=["POST"])
@admin.route("/activities/edit/<id>", methods=["GET", "POST"])
@requires_role(Roles.ADMIN)
def edit_activity(id=None):
    activity = db.session.execute(
        select(Activity).where(Activity.activity_id == id)
    ).scalar()

    form = EditActivityForm()

    if form.validate_on_submit():
        # Find the difference in hours between the start and end time
        delta = get_delta_hours(form.start_time.data, form.end_time.data)

        # Session must be at least 1 hour long
        if delta < 1:
            flash("Duration too short. Must be 1 hour minimum", "warning")
            return render_template("edit_activity.html", form=form)

        activity = set_activity_from_form(activity, form)
        db.session.commit()

        flash("Updated (not really)", "success")
        return redirect(url_for("admin.activities"))

        # Cannot be overlapping with existing activity of same type in facility
        # e.g. if LANESWIM in POOL 8am to 8pm exists then:
        # LANESWIM in POOL 12pm to 5pm should be rejected (any with start_time before 8pm should be, in fact)
        # GENERAL in POOL 12pm to 5pm should be accepted (assuming there are no other GENERAL POOL activities that day)
        # activity_id should be unique

    form = set_form_from_activity(form, activity)

    return render_template(
        "edit_page.html",
        title="Edit Activity",
        form=form,
        action=url_for("admin.edit_activity", id=id),
    )


@admin.route("/members")
@requires_role(Roles.ADMIN)
def members():
    members = db.session.execute(select(User).where(User.role == Roles.CUSTOMER)).all()
    members = [member[0].admin_data() for member in members]

    if len(members) == 0:
        return render_template(
            "show_db_data.html",
            title="Members",
            edit_action="admin.edit_activity",
        )

    return render_template(
        "show_db_data.html",
        title="Members",
        columns=members[0].keys(),
        data=members,
        edit_action="admin.edit_member",
        delete_from="user",
    )


@admin.route("/members/edit/", methods=["POST"])
@admin.route("/members/edit/<id>", methods=["POST", "GET"])
@requires_role(Roles.ADMIN)
def edit_member(id=None):
    member = db.session.execute(select(User).where(User.user_id == id)).scalar()
    form = EditUserForm(obj=member)

    # Hidden field that stores the id of the member being edited
    form.editing_user_id.data = member.user_id

    if form.validate_on_submit():
        # If username has been changed, check that it is unique
        if (
            get_user_by_username(form.username.data) is not None
            and form.username.data != member.username
        ):
            flash("Username taken", "warning")
            return redirect(url_for("admin.edit_member", user_id=id))

        # If email has been changed, check that it is unique
        if (
            get_user_by_email(form.email.data) is None
            and form.email.data != member.email
        ):
            flash("Email taken", "warning")
            return redirect(url_for("admin.edit_member", user_id=id))

        # TODO check if stripe_id is invalid.

        member.email = form.email.data
        member.username = form.username.data

        db.session.commit()

        flash("Updated", "success")
        return redirect(url_for("admin.members"))

    return render_template(
        "edit_page.html",
        title=member.username,
        form=form,
        action=url_for("admin.edit_member", id=id),
        danger_message="Note that  username, email must be unique. Only change the stripe_id if you know what you are doing",
    )


@admin.route("/facilities")
@requires_role(Roles.ADMIN)
def facilities():
    facils = db.session.execute(select(Facility)).all()
    facil_data = [facil[0].admin_data() for facil in facils]

    if len(facil_data) == 0:
        return render_template(
            "show_db_data.html",
            title="Activities",
            edit_action="admin.edit_activity",
        )

    return render_template(
        "show_db_data.html",
        title="Facilities",
        columns=facil_data[0].keys(),
        data=facil_data,
        edit_action="admin.edit_facility",
        delete_from="facility",
        message="Modifying or Deleting a Facility does not effect already booked sessions.",
    )


@admin.route("/facilities/edit", methods=["POST"])
@admin.route("/facilities/edit/<id>", methods=["POST", "GET"])
@requires_role(Roles.ADMIN)
def edit_facility(id=None):
    facility = db.session.execute(select(Facility).where(Facility.id == id)).scalar()

    form = EditFacilityForm(obj=facility)
    check_details = False

    if form.validate_on_submit():
        # Find the difference in hours between the start and end time
        delta = get_delta_hours(form.start_time.data, form.end_time.data)

        # Session must be at least 1 hour long
        if delta < 1:
            flash("Invalid opening and closing time.", "danger")
            return redirect(url_for("admin.edit_facility", id=id))

        if delta < 8:
            flash(
                f"The facility is open for {delta} hours. Is this correct?",
                "warning",
            )
            check_details = True

        if form.max_capacity.data <= 0:
            flash("Capacity set to 0 or less. Was this a mistake?", "warning")
            check_details = True

        form.populate_obj(facility)

        db.session.commit()
        flash("Updated", "success")
        if check_details:
            return redirect(url_for("admin.edit_facility", id=id))

        return redirect(url_for("admin.facilities"))

    return render_template(
        "edit_page.html",
        title=facility.facility_id,
        form=form,
        action=url_for("admin.edit_facility", id=id),
    )


@admin.route("/employees")
@requires_role(Roles.ADMIN)
def employees():
    employees = db.session.execute(
        select(User).where((User.role == Roles.ADMIN) | (User.role == Roles.EMPLOYEE))
    )
    employees = [em[0].admin_data() for em in employees]

    if len(employees) == 0:
        return render_template(
            "show_db_data.html",
            title="Employees",
            edit_action="admin.edit_activity",
        )

    return render_template(
        "show_db_data.html",
        title="Employees",
        columns=employees[0].keys(),
        data=employees,
        edit_action="admin.edit_employee",
        add_action="admin.add_employee",
        delete_from="user",
    )


@admin.route("/employees/edit", methods=["POST"])
@admin.route("/employees/edit/<id>", methods=["POST", "GET"])
@requires_role(Roles.ADMIN)
def edit_employee(id=None):
    employee = db.session.execute(select(User).where(User.user_id == id)).scalar()
    form = EditEmployeeForm()
    form.editing_user_id = employee.user_id

    if form.validate_on_submit():
        existing = get_user_by_username(form.username.data)
        if existing is not None:
            flash("Username already in use", "warning")
            return redirect(url_for("admin.edit_employee", id=id))

        employee.username = form.username.data
        employee.role = Roles(int(form.role.data))
        db.session.commit()

        flash("Updated", "success")
        return redirect(url_for("admin.employees"))

    # Can't set default role by passing employee so do it manually
    form.role.default = employee.role.value
    form.username.default = employee.username
    form.process()

    return render_template(
        "edit_page.html",
        title=employee.username,
        form=form,
        action=url_for("admin.edit_employee", id=id),
    )


@admin.route("/employees/add", methods=["POST", "GET"])
@requires_role(Roles.ADMIN)
def add_employee():
    form = AddEmployeeForm()

    if form.validate_on_submit():
        role = Roles(int(form.role.data))
        employee = create_user(
            "", form.username.data, hasher.hash(form.password.data), role
        )
        if employee is not None:
            flash("Created new Employee", "success")
            return redirect(url_for("admin.employees"))

        flash("Could not create employee", "warning")

    return render_template(
        "edit_page.html",
        title="Create Employee",
        form=form,

app/admin/templates/edit_page.html
{% extends "m_home.html" %}
{% from "macros.html" import render_form %}
{% block head %} {{title}} {% endblock %}
{% block styles %}

{% endblock %}

{% block content %}
<div class="container">
    <p class="text-danger">{{ danger_message }}</p>
</div>

{{render_form(form, action)}}
{% endblock %}

app/admin/templates/edit_pricing.html
{% extends "m_home.html" %}
{% from "macros.html" import render_field %}
{% block head %} {{title}} {% endblock %}
{% block styles %}

{% endblock %}

{% block content %}
<div class="container">
    <p class="text-danger">{{ danger_message }}</p>
</div>

<div class="container">
    <form action="{{url_for('admin.pricing')}}" method="post">
        {{ form.hidden_tag() }}
        {% for field in form if field.widget.input_type != 'hidden' %}
        {{render_field(field, class_="form-control")}}
        {% endfor %}
    </form>
    </div>
{% endblock %}

app/admin/templates/m_dashboard.html
{% extends "m_home.html" %}

{% block styles %}
    <link href="employee/static/m_dashboard.html" rel="stylesheet">
    
{% endblock %}

{% block head %} 
Dashboard 
{% endblock %}

{% block content %}
    <div class="row mb-5">
        <div class="d-flex justify-content-evenly w-100 p-3">
            <div class="list-group list-group-horizontal d-flex flex-wrap justify-content-center row-gap-3 column-gap-4">

                <div class="list-group-item d-flex flex-wrap border rounded">
                    <div class="d-flex flex-wrap flex-grow-1 align-content-between">
                        <img src="" alt="IMG" class="d-none d-md-flex p-3" width="120" height="120">
                        <h3 class="m-0 p-2 flex-grow-1 text-center">Members</h3>
                    </div>
                    <h3 class="m-0 pb-2 w-100 opacity-75 fw-bold text-center">500</h3>
                </div>

                <div class="list-group-item d-flex flex-wrap border rounded">
                    <div class="d-flex flex-wrap flex-grow-1 align-content-between">
                        <img src="" alt="IMG" class="d-none d-md-flex p-3" width="120" height="120">
                        <h3 class="m-0 p-2 flex-grow-1 text-center">Trainers</h3>
                    </div>
                    <h3 class="m-0 pb-2 w-100 opacity-75 fw-bold text-center">25</h3>
                </div>

                <div class="list-group-item d-flex flex-wrap border rounded">
                    <div class="d-flex flex-wrap flex-grow-1 align-content-between">
                        <img src="" alt="IMG" class="d-none d-md-flex p-3" width="120" height="120">
                        <h3 class="m-0 p-2 flex-grow-1 text-center">Sales</h3>
                    </div>
                    <h3 class="m-0 pb-2 w-100 opacity-75 fw-bold text-center">$500,000</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <ul class="nav nav-pills" id="graph-tabs" role="tablist">
            <li class="nav-item" role="presentation">
                <a class="nav-link active" id="members-tab" data-bs-toggle="tab" data-bs-target="#members" role="tab" aria-controls="members" aria-selected="true" href="#members">Members</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="trainers-tab" data-bs-toggle="tab" data-bs-target="#trainers" type="button" role="tab" aria-controls="trainers" aria-selected="false">Trainers</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="sales-tab" data-bs-toggle="tab" data-bs-target="#sales" type="button" role="tab" aria-controls="sales" aria-selected="false">Sales</a>
            </li>
        </ul>
        <div class="tab-content">
            <div id="members"class="tab-pane fade show active" role="tabpanel" aria-labelledby="members-tab">
                <h3>Members</h3>
                <canvas id="myChart"></canvas>
            </div>
            <div id="trainers" class="tab-pane fade" role="tabpanel" aria-labelledby="trainers-tab">
                <h3>Trainers</h3>
                <canvas id="myChart2"></canvas>
            </div>
            <div id="sales" class="tab-pane fade" role="tabpanel" aria-labelledby="sales-tab">
                <h3>Sales</h3>
                <canvas id="myChart3"></canvas>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script type="module" src="{{url_for('admin.static',filename='stats.js')}}"></script>
    </div>
    

{% endblock %}

app/admin/templates/m_home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Management</title>
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
    crossorigin="anonymous"/>
  
  {% block styles %}{% endblock %}  
</head>

<body>
  
  <div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar">
        <div class="position-sticky pt-3">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{url_for('admin.index')}}">
                Dashboard
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('admin.employees')}}">
                Employees
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('admin.members')}}">
                Members
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('admin.activities')}}">
                Activities
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('admin.facilities')}}">
                Facilities
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('admin.pricing')}}">
                Pricing
              </a>
            </li>
            <li class="nav-item">
              <hr>
            </li>
            <li class="nav-item">
                <h5>
                  {{current_user.username}}
                </h5>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('auth.logout')}}">
                Log Out
              </a>
            </li>
          </ul>
        </div>
      </nav>
  
      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <div class="container">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
              
                {% for category, message in messages %}
                <!-- A dissmiable alrt, coloured according to the category - these correspond to bootstrap stylings --> 
                  <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
                      {{ message }}
                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
              
        
                {% endfor %}
              {% endif %}
        {% endwith %}
        </div>
          <h1 class="h2">{% block head %}{% endblock %}</h1>
        </div>
  
        {% block content %} {% endblock %}
      </main>
    </div>
  </div>

</body>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>

</body>
</html>

app/admin/templates/show_db_data.html
{% extends "m_home.html" %}
{% from "macros.html" import render_admin_table %}

{% block head %} {{title}} {% endblock %}
{% block styles %}

{% endblock %}

{% block content %}
{% if add_action %}
<div class="d-flex mt-4 justify-content-end">
    <a class="btn btn-primary" href="{{url_for(add_action)}}">Add</a>
  </div>
{%endif%}

{% if message %}
{{message}}
{%endif%}

{% if columns %}
{{render_admin_table(columns, data, edit_action, delete_from)}}
{%else%}
<h3>No data to show.</h3>
{%endif%}

{% endblock %}