app/customer/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask import session as flask_session
from flask_login import current_user, logout_user
from app.utils import (
    requires_role,
    verify_password,
    update_password,
    update_email,
    update_username,
)
from app.models import Roles, Session, User
from app import db, stripe
from sqlalchemy import select
from app.forms import ActivitySelectForm, UpdateUserDetailsForm
from app.booking_utils import (
    CalanderItem,
    get_facility,
    get_facility_attendance,
    session_expired,
    get_users_next_sessions,
    group_session_list_by_day,
)
from werkzeug.urls import url_parse
from stripe import error
import datetime
import json


customer = Blueprint(
    "customer",
    __name__,
    template_folder="templates",
    static_folder="static",
    url_prefix="/customer",
)


@customer.route("/")
@requires_role(Roles.CUSTOMER)
def index():
    upcoming_sessions = get_users_next_sessions()
    grouped = group_session_list_by_day(upcoming_sessions)

    # grouped is not ordered so to display in chrono.
    #  order we use the sorted keys to access the dict.
    keys = sorted(grouped.keys())

    return render_template("dashboard.html", upcoming_sessions=grouped, keys=keys)


@customer.route("/membership")
@requires_role(Roles.CUSTOMER)
def membership():
    return render_template("membership.html")


@customer.route("/booking", methods=["GET", "POST"])
@requires_role(Roles.CUSTOMER)
def booking():
    form = ActivitySelectForm()
    sessions = None

    if form.validate_on_submit():
        c = CalanderItem(form.date.data, type=form.type.data)
        sessions = c.generate_overview()

        # Remove any sessions the user has already booked.
        sessions = [s for s in sessions if s not in flask_session["booked_sessions"]]
        return render_template("session_booking.html", form=form, activities=sessions)

    return render_template("session_booking.html", form=form)


@customer.route("/save_session", methods=["GET", "POST"])
@requires_role(Roles.CUSTOMER)
def save_session():
    request.form.items()

    sessions = list(request.form.items())

    # Save provisionally booked sessions.
    flask_session["booked_sessions"] += [
        sess[1] for sess in sessions if sess[1] not in flask_session["booked_sessions"]
    ]
    flask_session.modified = True
    flash("Added to basket", "success")

    return redirect(url_for("customer.booking"))


@customer.route("/manage_sessions")
@requires_role(Roles.CUSTOMER)
def manage_sessions():
    sessions = current_user.sessions

    sessions = [
        (sess, True) if session_expired(sess) else (sess, False) for sess in sessions
    ]

    return render_template("session_management.html", sessions=sessions)


@customer.route("/delete_session/<id>", methods=["GET", "POST"])
@requires_role(Roles.CUSTOMER)
def delete_session(id):
    session = db.session.execute(
        select(Session).where(Session.session_id == id)
    ).scalar()

    session.users.remove(current_user)

    # if a session has no attendees then remove it from the db.
    if len(session.users) == 0:
        db.session.delete(session)

    db.session.commit()
    return redirect(url_for("customer.manage_sessions"))


@customer.route("/delete_basket/<id>", methods=["GET", "POST"])
@requires_role(Roles.CUSTOMER)
def delete_basket(id):
    flask_session["booked_sessions"].pop(int(id))
    flask_session.modified = True
    return redirect(url_for("customer.checkout"))


@customer.route("/checkout")
@requires_role(Roles.CUSTOMER)
def checkout():
    sess_objs = []
    valid = True
    for sess in flask_session["booked_sessions"]:
        s = Session.from_unique_code(sess)

        # If a session already exists then use that.
        existing = db.session.execute(
            select(Session).where(
                (Session.start_time == s.start_time)
                & (Session.end_time == s.end_time)
                & (Session.facility_id == s.facility_id)
                & (Session.session_type == s.session_type)
            )
        ).scalar()

        if existing:
            s = existing

        attendance = get_facility_attendance(s)
        facility = get_facility(s)

        if attendance >= facility.max_capacity:
            flash(f" {s} at max capacity", "warning")
            valid = False

        # Provisionally book the user onto the session
        # Not final until db.commit.
        s.users.append(current_user)
        sess_objs.append(s)

        # Don't let user book multiple sessions that start at the same time.
        # The set removes duplicates from the list, if the set has a different length then duplicate start times existed.
        if len(set([s.start_time for s in sess_objs])) != len(sess_objs):
            flash(
                "Timetable clash in selected sessions. You can only attend 1 session per hour",
                "warning",
            )
            valid = False

        start_times = [s.start_time for s in sess_objs]
        # Show an alert for any timetable clashes.
        for dupe in {time for time in start_times if start_times.count(time) > 1}:
            flash(
                f"Time table clash at  {dupe}. Please resolve before payment", "warning"
            )
            valid = False
    # return flask_session["booked_sessions"]
    return render_template("basket.html", sessions=sess_objs, valid=valid)


# @customer.route("/") // if possible, want to preprocess today's available activities without pressing date buttons
@customer.route("/get_sessions")
@customer.route("/get_sessions/<data>")
@requires_role(Roles.CUSTOMER)
def get_sessions(data=None):  # data: YYYY-MM-DD-type
    if data is None:
        date = datetime.date.today()
        type = "general"

    else:
        year = int(data.split("-")[0])
        month = int(data.split("-")[1])
        datenum = int(data.split("-")[2])
        date = datetime.date(year, month, datenum)

        type = data.split("-")[3]

    c = CalanderItem(date, type)
    sessions = c.create_JSON_from_activities()
    js = json.loads(sessions)

    return js


@customer.route("/settings", methods=["POST", "GET"])
@requires_role(Roles.CUSTOMER)
def settings():
    form = UpdateUserDetailsForm(
        data={"email": current_user.email, "username": current_user.username}
    )
    if form.validate_on_submit():
        print(request.form)
        # Make sure user has authenticated
        if not verify_password(form.current_password.data):
            flash("Current password invalid", "warning")
            return redirect(url_for("customer.settings"))

        # If a new password has been entered then set it.
        if form.new_password.data:
            update_password(form.new_password.data)

        # Update username if it has changed and is not taken
        if form.username.data != current_user.username:
            if update_username(form.username.data) is None:
                flash("Could not use that username", "warning")
                return redirect(url_for("customer.settings"))

        # Update email if it has changed and is valid + not taken
        if form.email.data != current_user.email:
            if update_email(form.email.data) is None:
                flash("Could not use that email", "warning")
                return redirect(url_for("customer.settings"))

        flash("Updated account", "success")

    return render_template("settings.html", form=form)


@customer.route("/settings/delete_account", methods=["POST", "GET"])
@requires_role(Roles.CUSTOMER)
def delete_account():
    # Make user reauthenticate before deleting
    if request.method == "GET" and url_parse(request.referrer).path != url_for(
        "auth.reauth"
    ):
        flash("Your account will be deleted if you submit this form.", "danger")
        return redirect(url_for("auth.reauth", next=url_for("customer.delete_account")))

    if current_user.stripe_id is not None:
        try:
            stripe.Customer.delete(current_user.stripe_id)
        except error.InvalidRequestError as e:
            print(str(e))

    user_id = current_user.user_id
    logout_user()

    user = db.session.execute(select(User).where(User.user_id == user_id)).scalar()
    db.session.delete(user)
    db.session.commit()
    flash("Account Deleted", "success")

    return redirect(url_for("main.index"))


@customer.route("/settings/payment_info")
@requires_role(Roles.CUSTOMER)
def payment_info():
    customer = None
    if current_user.stripe_id is None:
        customer = stripe.Customer.create(email=current_user.email)
    if customer:
        current_user.stripe_id = customer.id
        db.session.commit()

    portal = None
    try:
        portal = stripe.billing_portal.Session.create(
            customer=current_user.stripe_id,
            return_url=url_for("customer.settings", _external=True),
        )
    except error.InvalidRequestError:
        flash("Could not create billing portal", "warning")

    if portal is not None:
        return redirect(portal.url)

    return redirect(url_for("customer.settings"))

app/customer/templates/account.html
{% extends "base.html" %}
{% block styles %}
<link rel="stylesheet" type="text/css" href="{{url_for('customer.static', filename='account.css')}}" />
{% endblock %}

{% block content %}
<div class="form-container">
  <P></P>
  <h1>Account</h1>
  <form action="" method="post" enctype="multipart/form-data">
    <div class="form-group">
      <img src="P_images/blank_photo.png" alt="Profile picture">
      <p></p>
			<a type="button" href="#" class="btn btn-primary mr-3" role="button">my booking</a>  <!-- booking page needs to add in here -->
			<a type="button" href="update_profile.html" class="btn btn-secondary mr-3" role="button">update my profile</a>
      </div>
    </div>  
  </form>
{% endblock %}

app/customer/templates/basket.html
{% extends "base.html" %}

{% block title %} Basket {% endblock %}

{% block styles %}
<link rel="stylesheet" href="{{url_for('customer.static', filename='checkout.css')}}">
{% endblock %}

{% block content %}
<h1> You Basket</h1>
{% if sessions %}
 <div>
    <ul>
        {% for session in sessions %}
        <h4>{{session.display_date()}}</h4>
        <li id="{{loop.index0}}">
             {{session.display_facility()}}
             {{session.display_session_type()}}
             {{session.display_start_time()}}-{{session.display_end_time()}}
             <a href="{{url_for('customer.delete_basket', id = loop.index0)}}">Delete</a>
        </li>
        {% endfor %}
    </ul>
    <form method="post" action="{{url_for('auth.booking_checkout_session')}}">
      {% if valid %}
        <button>Go to Payment</button>
      {% else %}
        <button disabled aria-disabled="true">Go to Payment</button>
      {% endif %}
        
 </div>
 {% else %}
 <div>
    <p>You haven't booked any sessions yet.</p>
 </div>
 {% endif %}
 {% endblock %}

app/customer/templates/dashboard.html
{% extends "base.html" %}

{%block styles%}
<link href="{{url_for('customer.static',filename='dashboard.css')}}" rel="stylesheet" type="text/css">
<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
<script src="{{url_for('customer.static',filename='dashboard.js')}}" defer></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
{% endblock %}



{% block title %} Dashboard {% endblock %}
{% block content %}


<div class="container-fluid mt-4 dash">
    <div class="row">
        <div class="col-md-5 border-end mb-4" id="left-section">
            <!-- Calendar -->
            <div class="row" id="calendar">
                <div class="d-flex justify-content-between">
                    <h3 class="month-year"></h3>
                    <i class="bx bx-chevron bx-chevron-right bx-md opacity-75"></i>
                </div>

                <div class="calendar">
                    <ul class="date-days">
                        <li>Sun</li>
                        <li>Mon</li>
                        <li>Tue</li>
                        <li>Wed</li>
                        <li>Thu</li>
                        <li>Fri</li>
                        <li>Sat</li>
                    </ul>
                    <ul class="date-number">
                    </ul>
                </div>

            </div>
            <br>
            <!-- List booked sessions -->
            <div class="row" id="select-session-type">
                <h3 class="m-0">Your Upcoming Sessions</h3>
                <!--  Keys are sorted so we use these to access the dict in the correct order. -->
                {% for date in keys %}
                <!-- formatting gives e.g Thu 23 Feb -->
                <h5 class="d-flex mt-3 mb-2 opacity-75">{{date.strftime("%a %d %b")}}</h5>
                <div class="list-group">
                    {% for sess in upcoming_sessions[date] %}
                    <a href="{{url_for('customer.manage_sessions')}}"
                        class="list-group-item list-group-item-action d-flex gap-5 p-2 justify-content-between">
                        <p class="d-flex py-1 ps-2 m-0 text-center align-content-center">{{ sess.display_start_time() }} <br> to <br> {{
                            sess.display_end_time() }}</p>
                        <div class="d-flex w-100 gap-4 flex-wrap align-content-center">
                            <div>
                                <h5 class="m-0">{{ sess.display_session_type() }}</h5>
                                <p class="m-0 text-secondary">{{ sess.display_facility() }}</p>
                            </div>

                        </div>
                    </a>
                    {%endfor%}
                </div>
                {% endfor %}

            </div>
        </div>
        <div class="col-md-7 mb-4" id="right-section">
            <div class="row">
                <div class="col">
                    <h3 id="date-selected"></h3>
                </div>
                <div class="col-sm col-md-">
                    <div class="btn-group pb-3 float-start float-sm-end" role="group" aria-label="Activity types">
                        <input type="radio" class="btn-check typeToParse" name="btnradio" id="general"
                            autocomplete="off" checked>
                        <label class="btn btn-outline-success" for="general">General</label>

                        <input type="radio" class="btn-check typeToParse" name="btnradio" id="class" autocomplete="off">
                        <label class="btn btn-outline-warning" for="class">Class</label>

                        <input type="radio" class="btn-check typeToParse" name="btnradio" id="team" autocomplete="off">
                        <label class="btn btn-outline-danger" for="team">Team</label>

                        <input type="radio" class="btn-check typeToParse" name="btnradio" id="all" autocomplete="off">
                        <label class="btn btn-outline-primary" for="all">All</label>
                    </div>
                </div>
            </div>

            <div class="row session-container">
                <!-- example layout
                <div class="list-group mb-4">
                    <a href="{{url_for('customer.booking')}}" class="list-group-item list-group-item-action d-sm-flex p-3">
                        <div class="d-flex gap-5 w-100">
                            <i class="bx bx-swim bx-lg d-none d-md-flex m-auto py-2"></i>
                            <div class="d-inline w-100">
                                <div>
                                    <h5 class="d-flex justify-content-between mb-3 text-secondary">9:00 - 10:00
                                    <span class="badge bg-secondary rounded-pill">50</span></h5>
                                </div>
                                <div class="">
                                    <h5 class="m-0">Swimming</h5>
                                    <p class="m-0 text-secondary">Swimming Pool</p>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                -->
            </div>

            <div class="row">
                <h3 class="p-0"> Membership Details</h3>
                {% if current_user.display_membership_type() != "None" %}
                <p>Your {{current_user.display_membership_type()}} Membership expires at {{
                    current_user.membership_expiration_date.strftime("%a %d %b %Y") }}</p>
                {% else %}
                <p>You do not currently have a membership.</p>
                <a class="btn btn-lg btn-outline-primary" href="{{url_for('customer.membership')}}">Purchase one
                    now?</a>
                {% endif %}
            </div>


        </div>

    </div>
    <div class="row p-2"></div>
</div>

{% endblock %}

app/customer/templates/membership.html
{% extends "base.html" %}
{% block title %} Session Booking {% endblock %}

{% block content %}
    <main>
    <h1>Become a member!</h1>  
      <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        <div class="col">
          <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
              <h4 class="my-0 fw-normal">Monthly</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title">£35<small class="text-muted fw-light">/mo</small></h1>
              <a class="w-100 btn btn-lg btn-primary" href="{{url_for('auth.monthly_membership_checkout')}}">Join now</a>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
              <h4 class="my-0 fw-normal">Annual</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title">£300<small class="text-muted fw-light">/yr</small></h1>
              <a class="w-100 btn btn-lg btn-primary" href="{{url_for('auth.annual_membership_checkout')}}">Join now (@25/mo)</a>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
              <h4 class="my-0 fw-normal">Pay per Session</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title">£9.99<small class="text-muted fw-light">/session</small></h1>
              <p>15% discount when booking 3 or more sessions that occur within 7 days of each other</p>
              <a class="w-100 btn btn-lg btn-outline-primary" href="{{url_for('customer.booking')}}">Book Now</a>
            </div>
          </div>
        </div>
      </div>
 {% endblock %}

app/customer/templates/session_booking.html
{% extends "base.html" %}
{% block title %} Session Booking {% endblock %}

{% block content %}
<h1>Book a session</h1>
<form method="POST" action="{{url_for('customer.booking')}}">
    {{form.hidden_tag()}}
    {% for field in form if field.label.text != "CSRF Token" %}
        {%if field.type == "RadioField"%}
        {% for choice in field%}
        {{choice.label}}
        {{choice}}
        <br>
        {%endfor%}
    {%else%}
    {{field.label}}
    {{field}}
    <br>
    {%endif%}
    {%endfor%}
</form>
<h2>Available sessions: </h2>
{% if activities%}
<h4>{{activities[0]}}</h4>
<br>
<form method="post", action="{{url_for('customer.save_session')}}">
{%for a in activities[1]%}
{%set outerloop = loop%}
    <h4>{{a.facility}} - {{a.activity}}</h4>
    {%for sess in a.sessions%}

    <input type="checkbox" value="{{sess.unique_code()}}"
     id="{{sess.unique_code()}}" name="{{sess.unique_code()}}">
     <label for="{{sess.unique_code()}}"> 
    {{sess.display_start_time()}} to 
    {{sess.display_end_time()}}
    </label>
    <br>
    {%endfor%}
    <hr>
{%endfor%}
<button type="submit">Book</button>
</form>

 {%endif%}
 {% endblock %}

app/customer/templates/session_management.html
{% extends "base.html" %}

{% block title %} Manage Sessions {% endblock %}

{% block content %}
<h1> Manage Sessions</h1>
{% if sessions %}
 <div>
    <ul>
        {% for session, is_expired in sessions %}
        <h4>{{session.display_date()}}</h4>
        <li>
             {{session.display_facility()}}
             {{session.display_session_type()}}
             {{session.display_start_time()}}-{{session.display_end_time()}}

             {% if current_user.role == Roles.EMPLOYEE %}
               {% if is_expired%}
               <a href="{{url_for('employee.booking')}}">Book again?</a>
               {% else %}
               <a href="{{url_for('employee.delete_session', id = session.session_id)}}">Delete</a>
               {% endif %}
            {% else %}
               {% if is_expired%}
               <a href="{{url_for('customer.booking')}}">Book again?</a>
               {% else %}
               <a href="{{url_for('customer.delete_session', id = session.session_id)}}">Delete</a>
               {% endif %}
             {% endif %}


        </li>
        {% endfor %}
    </ul>
 </div>
 {% else %}
 <div>
    <p>You haven't booked any sessions yet.</p>
 </div>
 {% endif %}
 {% endblock %}

app/customer/templates/settings.html
{% extends 'base.html' %}
{% from 'macros.html' import render_field, render_form %}


{% if current_user.role == Roles.EMPLOYEE %}
{% set  mode = "employee" %}
{% else %}
{% set mode = "customer" %}
{% endif %}
{%block styles %}



{% endblock %}
{% block content %}
<h1 class="text-center mb-4">Update Profile</h1>
    {{render_form(form, url_for(mode + '.settings'))}}
    <hr>
    <div class="container clearfix">
      <a class="btn btn-danger float-end" href="{{url_for(mode + '.delete_account')}}">Delete Account</a>
      <a class="btn btn-warning float-start" href="{{url_for(mode + '.payment_info')}}">View/Edit Payment Details</a>
    </div>
{% endblock %}